config/routes.rb
Rails.application.routes.draw do
  resources :fugas
  get 'profile/show'
  get 'profile/edit'
  get 'profile/update'
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/books/:id" => "books#show"

  # resourcesで生成されるルーティングの拡張
  resources :publishers do
    resources :books

    # 個別のリソースに対するアクション
    member do
      get 'detail'
    end

    # 全体のリソースに対するアクション
    collection do
      get 'search'
    end
  end

  resource :profile, only: %i{show edit update}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors
  has_many :books, through: :book_authors
end

app/models/book.rb
class Book < ApplicationRecord

  enum status: %w(reservation now_on_sale end_of_print)

  # ハッシュ型で定義することもできる
  # enum status: {reservation: 0, now_on_sale: 1, end_of_print: 2}

  scope :costly, -> {where("price > ?", 3000)}
  scope :written_about, -> (theme) {where("name like ?", "%#{theme}%")}
  default_scope -> {order("published_on desc")}

  belongs_to :publisher

  has_many :book_authors
  has_many :authors, through: :book_authors

  validates :name, presence: true
  validates :name, length: {maximum:15}
  validates :price, numericality: {greater_than_or_equel_to:0}

  validate do |book|
    if book.name.include?("exercise")
      book.errors[:name] << "I don't like exercise."
    end
  end

  before_validation do |book|
    book.name = book.name.gsub(/Cat/) do |matched|
      "lovely #{matched}"
    end
  end

  # あるいはメソッドを使って以下のようにもかける
  # before_validation :add_lovely_to_cat
  # def add_lovely_to_cat
  #   book.name = book.name.gsub(/Cat/) do |matched|
  #     "lovely #{matched}"
  #   end
  # end

  after_destroy do |book|
    Rails.logger.info "Book is deleted: #{book.attributes.inspect}"
  end

  def high_price?
    price >= 5000
  end

  after_destroy :if => :high_price? do |book|
    Rails.logger.warn "Book with high price is deleted: #{book.attributes.inspect}"
    Rails.logger.warn "Please check!!"
  end
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/fuga.rb
class Fuga < ApplicationRecord
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # CSRF脆弱性攻撃に対する挙動（CSRF対策）
  # protect_from_forgery with: :exception

  # 以下のようにブロックを用いてコールバックを定義することも可能
  # before_action do
  #   redirect_to access_denied_path if params[:token].blank?
  # end

  # アクションコールバックのスキップ(skip_before_action, skip_after_action, skip_around_action)
  # before_action :require_login
  # def require_login
  #   # ログインを確認し、非ログイン時にリダイレクトする処理
  # end

  # variant
  before_action :detect_mobile_variant

  private
  def detect_mobile_variant
    request.variant = :mobile if request.user_agent =~ /iPhone/
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # def show
  #   @book = Book.find(params[:id])
  #   respond_to do |format|
  #     format.html
  #     format.csv
  #     format.json
  #   end
  # end
  #
  # before_action :set_book, only: [:show, :edit, :update, :destroy]
  #
  # def set_book
  #   @book = Book.find(params[:id])
  # end

  # def show
  #   @book = Book.find(params[:id])
  #   render :show
  # end

  # renderの省略
  # def show
  #   @book = Book.find(params[:id])
  # end

  # コンテンツのタイプによって表示を出し分ける
  # def show
  #   @book = Book.find(params[:id])
  #   respond_to do |format|
  #     format.html
  #     format.csv
  #   end
  # end

  # jbuilder
  def show
    @book = Book.find(params[:id])
    respond_to do |format|
      format.json
    end
  end
end

app/controllers/fugas_controller.rb
class FugasController < ApplicationController
  before_action :set_fuga, only: [:show, :edit, :update, :destroy]

  # GET /fugas
  # GET /fugas.json
  def index
    @fugas = Fuga.all
  end

  # GET /fugas/1
  # GET /fugas/1.json
  def show
  end

  # GET /fugas/new
  def new
    @fuga = Fuga.new
  end

  # GET /fugas/1/edit
  def edit
  end

  # POST /fugas
  # POST /fugas.json
  def create
    @fuga = Fuga.new(fuga_params)

    respond_to do |format|
      if @fuga.save
        format.html { redirect_to @fuga, notice: 'Fuga was successfully created.' }
        format.json { render :show, status: :created, location: @fuga }
      else
        format.html { render :new }
        format.json { render json: @fuga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fugas/1
  # PATCH/PUT /fugas/1.json
  def update
    respond_to do |format|
      if @fuga.update(fuga_params)
        format.html { redirect_to @fuga, notice: 'Fuga was successfully updated.' }
        format.json { render :show, status: :ok, location: @fuga }
      else
        format.html { render :edit }
        format.json { render json: @fuga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fugas/1
  # DELETE /fugas/1.json
  def destroy
    @fuga.destroy
    respond_to do |format|
      format.html { redirect_to fugas_url, notice: 'Fuga was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fuga
      @fuga = Fuga.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fuga_params
      params.fetch(:fuga, {})
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
  end

  def edit
  end

  def update
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  # 一覧表示画面を表示する
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  # 詳細表示画面を表示する
  def show
  end

  # GET /tasks/new
  # 新規登録画面を表示する
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  # 編集画面を表示する
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  # 新規登録処理をして、詳細画面を表示する（POST）
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  # 更新処理をして、詳細画面を表示する（PUT/PATCH）
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  # 削除処理をして、一覧画面を表示する
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def to_hankaku(str)
    str.tr('Ａ-Ｚａ-ｚ', 'A-Za-z')
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/fugas_helper.rb
module FugasHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/books/show.csv.erb
書籍名、価格、発売日
<%= [@book.name, @book.price, @book.published_on.to_s].join(',') %>

app/views/books/show.html+mobile.erb
<h1>本の情報(for mobile)</h1>
<dl>
  <dt>書籍名</dt>
  <dd><%= @book.name %></dd>
  <dt>価格</dt>
  <dd><%= @book.price %></dd>
  <dt>発売日</dt>
  <dd><%= @book.published_on.to_s %></dd>
</dl>

app/views/books/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Document</title>
</head>
<body>
  <h1>本の情報</h1>
  <dl>
    <dt>書籍名</dt>
    <dd><%= @book.name %></dd>
    <dt>価格</dt>
    <dd><%= @book.price %></dd>
    <dt>発売日</dt>
    <dd><%= @book.published_on.to_s %></dd>
  </dl>
</body>
</html>

app/views/fugas/_form.html.erb
<%= form_with(model: fuga, local: true) do |form| %>
  <% if fuga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fuga.errors.count, "error") %> prohibited this fuga from being saved:</h2>

      <ul>
      <% fuga.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fugas/edit.html.erb
<h1>Editing Fuga</h1>

<%= render 'form', fuga: @fuga %>

<%= link_to 'Show', @fuga %> |
<%= link_to 'Back', fugas_path %>

app/views/fugas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fugas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fugas.each do |fuga| %>
      <tr>
        <td><%= link_to 'Show', fuga %></td>
        <td><%= link_to 'Edit', edit_fuga_path(fuga) %></td>
        <td><%= link_to 'Destroy', fuga, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fuga', new_fuga_path %>

app/views/fugas/new.html.erb
<h1>New Fuga</h1>

<%= render 'form', fuga: @fuga %>

<%= link_to 'Back', fugas_path %>

app/views/fugas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_fuga_path(@fuga) %> |
<%= link_to 'Back', fugas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookAdmin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.content %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>